/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layaot;

/**
 *
 * @author Sistemas-12
 */
public class PnlGridLayaout extends javax.swing.JPanel {

    /**
     * Creates new form PnlGridLayaout
     */
    public PnlGridLayaout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(4, 2));

        jLabel6.setText("jLabel6");
        add(jLabel6);

        jTextField8.setText("jTextField8");
        add(jTextField8);

        jLabel5.setText("jLabel5");
        add(jLabel5);

        jTextField9.setText("jTextField9");
        add(jTextField9);

        jLabel7.setText("jLabel7");
        add(jLabel7);

        jTextField10.setText("jTextField10");
        add(jTextField10);

        jLabel8.setText("jLabel8");
        add(jLabel8);

        jTextField11.setText("jTextField11");
        add(jTextField11);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
